/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import com.sun.awt.AWTUtilities;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author sistems
 */
public class frmModulos extends javax.swing.JFrame {

    /**
     * Creates new form frmAgregar
     */
    public frmModulos() {
        this.setUndecorated(true);
        //inicializar componentes
        initComponents();
        this.setLocationRelativeTo(null); //centrar formulario
        //redondear bordes
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 27, 27);
        AWTUtilities.setWindowShape(this, forma);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        icoConfi1 = new javax.swing.JLabel();
        icoConfi4 = new javax.swing.JLabel();
        icoConfi6 = new javax.swing.JLabel();
        icoConfi2 = new javax.swing.JLabel();
        icoConfi7 = new javax.swing.JLabel();
        btnCategoria = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        icoConfi8 = new javax.swing.JLabel();
        btnCliente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        icoConfi9 = new javax.swing.JLabel();
        icoConfi10 = new javax.swing.JLabel();
        btnInventario = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        icoConfi11 = new javax.swing.JLabel();
        icoConfi12 = new javax.swing.JLabel();
        btnVenta = new javax.swing.JButton();
        btnCompra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icoConfi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar.png"))); // NOI18N
        jPanel1.add(icoConfi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 330, 100, 90));

        icoConfi4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addCategoria.png"))); // NOI18N
        jPanel1.add(icoConfi4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 110, 90, 90));

        icoConfi6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addProveedor.png"))); // NOI18N
        jPanel1.add(icoConfi6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 100, 100));

        icoConfi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addEmpleado.png"))); // NOI18N
        jPanel1.add(icoConfi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 90, -1));

        icoConfi7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/producto100.png"))); // NOI18N
        jPanel1.add(icoConfi7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 100, 80));

        btnCategoria.setBackground(new java.awt.Color(255, 102, 0));
        btnCategoria.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnCategoria.setForeground(new java.awt.Color(51, 153, 255));
        btnCategoria.setText("Categorias");
        btnCategoria.setBorder(null);
        btnCategoria.setContentAreaFilled(false);
        btnCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCategoria.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 130, 110));

        btnRegresar.setBackground(new java.awt.Color(255, 102, 0));
        btnRegresar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(51, 153, 255));
        btnRegresar.setText("Regresar a Inicio");
        btnRegresar.setBorder(null);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegresar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 320, 140, 120));

        btnProducto.setBackground(new java.awt.Color(255, 102, 0));
        btnProducto.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnProducto.setForeground(new java.awt.Color(51, 153, 255));
        btnProducto.setText("Productos");
        btnProducto.setBorder(null);
        btnProducto.setContentAreaFilled(false);
        btnProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProducto.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 130, 110));

        btnEmpleados.setBackground(new java.awt.Color(255, 102, 0));
        btnEmpleados.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnEmpleados.setForeground(new java.awt.Color(51, 153, 255));
        btnEmpleados.setText("Empleados");
        btnEmpleados.setBorder(null);
        btnEmpleados.setContentAreaFilled(false);
        btnEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmpleados.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 110, 140));

        btnProveedor.setBackground(new java.awt.Color(255, 102, 0));
        btnProveedor.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnProveedor.setForeground(new java.awt.Color(51, 153, 255));
        btnProveedor.setText(" Proveedores");
        btnProveedor.setBorder(null);
        btnProveedor.setContentAreaFilled(false);
        btnProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProveedor.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btnProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 150, 120));

        icoConfi8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        icoConfi8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addCliente.png"))); // NOI18N
        jPanel1.add(icoConfi8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 90, 80));

        btnCliente.setBackground(new java.awt.Color(255, 102, 0));
        btnCliente.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(51, 153, 255));
        btnCliente.setText("Clientes");
        btnCliente.setBorder(null);
        btnCliente.setContentAreaFilled(false);
        btnCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCliente.setVerifyInputWhenFocusTarget(false);
        btnCliente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 130, 120));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setForeground(new java.awt.Color(51, 153, 255));
        jPanel2.setName(""); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setBackground(new java.awt.Color(255, 102, 0));
        btnCerrar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 102, 0));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Multiply_32px.png"))); // NOI18N
        btnCerrar.setBorder(null);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setVerifyInputWhenFocusTarget(false);
        btnCerrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 30, 30));

        btnMinimizar.setBackground(new java.awt.Color(255, 102, 0));
        btnMinimizar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnMinimizar.setForeground(new java.awt.Color(255, 102, 0));
        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        btnMinimizar.setBorder(null);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMinimizar.setVerifyInputWhenFocusTarget(false);
        btnMinimizar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 35));

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));
        jPanel4.setForeground(new java.awt.Color(51, 153, 255));
        jPanel4.setName(""); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 1060, 35));

        icoConfi9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario129.png"))); // NOI18N
        jPanel1.add(icoConfi9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, 100, 100));

        icoConfi10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja (1).png"))); // NOI18N
        jPanel1.add(icoConfi10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 70, 90));

        btnInventario.setBackground(new java.awt.Color(255, 102, 0));
        btnInventario.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(51, 153, 255));
        btnInventario.setText("Inventario");
        btnInventario.setBorder(null);
        btnInventario.setContentAreaFilled(false);
        btnInventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInventario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 110, 110));

        btnUsuarios.setBackground(new java.awt.Color(255, 102, 0));
        btnUsuarios.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(51, 153, 255));
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setBorder(null);
        btnUsuarios.setContentAreaFilled(false);
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuarios.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 100, 120));

        icoConfi11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comprar.png"))); // NOI18N
        jPanel1.add(icoConfi11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 100, 100));

        icoConfi12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vender.png"))); // NOI18N
        jPanel1.add(icoConfi12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 100, 80));

        btnVenta.setBackground(new java.awt.Color(255, 102, 0));
        btnVenta.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnVenta.setForeground(new java.awt.Color(51, 153, 255));
        btnVenta.setText("Venta");
        btnVenta.setBorder(null);
        btnVenta.setContentAreaFilled(false);
        btnVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVenta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 130, 110));

        btnCompra.setBackground(new java.awt.Color(255, 102, 0));
        btnCompra.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnCompra.setForeground(new java.awt.Color(51, 153, 255));
        btnCompra.setText("Compra");
        btnCompra.setBorder(null);
        btnCompra.setContentAreaFilled(false);
        btnCompra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCompra.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });
        jPanel1.add(btnCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 120, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        // TODO add your handling code here:

        frmModuloCliente verformulario2 = new frmModuloCliente();
        //línea 2-hacemos visible el formulario que queremos llamar 
        verformulario2.setVisible(true);
        this.setVisible(false);//oculta el jFrame que estes usando
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        //pasar de una pestaña a otra
        
           inicio verformulario2 =new inicio();
        //línea 2-hacemos visible el formulario que queremos llamar
        verformulario2.setVisible(true);

        this.setVisible(false);//oculta el jFrame que estes usando
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);

    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:

        //línea 1-instanciamos un objeto de la clase Formulario2.java
        inicio verformulario2 = new inicio();
        //línea 2-hacemos visible el formulario que queremos llamar
        verformulario2.setVisible(true);

        this.setVisible(false);//oculta el jFrame que estes usando
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
        
             //línea 1-instanciamos un objeto de la clase Formulario2.java
        frmModuloInventario ir = new  frmModuloInventario();
        //línea 2-hacemos visible el formulario que queremos llamar
        ir.setVisible(true);
         this.setVisible(false);//oculta el jFrame que estes usando
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        
                  //línea 1-instanciamos un objeto de la clase Formulario2.java
        frmModuloUsuario ir = new  frmModuloUsuario();
        //línea 2-hacemos visible el formulario que queremos llamar
        ir.setVisible(true);
         this.setVisible(false);//oculta el jFrame que estes usando
        
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        // TODO add your handling code here:
        
                  //línea 1-instanciamos un objeto de la clase Formulario2.java
        frmModuloEmpleado ir = new  frmModuloEmpleado();
        //línea 2-hacemos visible el formulario que queremos llamar
        ir.setVisible(true);
         this.setVisible(false);//oculta el jFrame que estes usando
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        // TODO add your handling code here:
        
                  //línea 1-instanciamos un objeto de la clase Formulario2.java
        frmModuloEmpleado ir = new  frmModuloEmpleado();
        //línea 2-hacemos visible el formulario que queremos llamar
        ir.setVisible(true);
         this.setVisible(false);//oculta el jFrame que estes usando
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        // TODO add your handling code here:
        
                  //línea 1-instanciamos un objeto de la clase Formulario2.java
        frmModuloProveedor ir = new  frmModuloProveedor();
        //línea 2-hacemos visible el formulario que queremos llamar
        ir.setVisible(true);
         this.setVisible(false);//oculta el jFrame que estes usando
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaActionPerformed
        // TODO add your handling code here:
                  //línea 1-instanciamos un objeto de la clase Formulario2.java
        frmModuloCategoria ir = new  frmModuloCategoria();
        //línea 2-hacemos visible el formulario que queremos llamar
        ir.setVisible(true);
         this.setVisible(false);//oculta el jFrame que estes usando
    }//GEN-LAST:event_btnCategoriaActionPerformed

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        // TODO add your handling code here:
         frmModuloDetalleVent ir = new  frmModuloDetalleVent();
        //línea 2-hacemos visible el formulario que queremos llamar
        ir.setVisible(true);
         this.setVisible(false);//oculta el jFrame que estes usando
        
    }//GEN-LAST:event_btnVentaActionPerformed

    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
        // TODO add your handling code here:
        
        frmModuloDetalleCompra ir = new  frmModuloDetalleCompra();
        //línea 2-hacemos visible el formulario que queremos llamar
        ir.setVisible(true);
         this.setVisible(false);//oculta el jFrame que estes usand
    }//GEN-LAST:event_btnCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmModulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmModulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmModulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmModulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmModulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategoria;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVenta;
    private javax.swing.JLabel icoConfi1;
    private javax.swing.JLabel icoConfi10;
    private javax.swing.JLabel icoConfi11;
    private javax.swing.JLabel icoConfi12;
    private javax.swing.JLabel icoConfi2;
    private javax.swing.JLabel icoConfi4;
    private javax.swing.JLabel icoConfi6;
    private javax.swing.JLabel icoConfi7;
    private javax.swing.JLabel icoConfi8;
    private javax.swing.JLabel icoConfi9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
